import { expect, type Page } from "@playwright/test";

const RAKUTEN_STATEMENT_PDF_BASE64 =
  "JVBERi0xLjcKJcK1wrYKJSBXcml0dGVuIGJ5IE11UERGIDEuMjcuMgoKMSAwIG9iago8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvSW5mbzw8L1Byb2R1Y2VyKE11UERGIDEuMjcuMik+Pj4+CmVuZG9iagoKMiAwIG9iago8PC9UeXBlL1BhZ2VzL0NvdW50IDEvS2lkc1s0IDAgUl0+PgplbmRvYmoKCjMgMCBvYmoKPDwvRm9udDw8L2hlbHYgNSAwIFI+Pj4+CmVuZG9iagoKNCAwIG9iago8PC9UeXBlL1BhZ2UvTWVkaWFCb3hbMCAwIDU5NSA4NDJdL1JvdGF0ZSAwL1Jlc291cmNlcyAzIDAgUi9QYXJlbnQgMiAwIFIvQ29udGVudHNbNiAwIFIgNyAwIFIgOCAwIFIgOSAwIFIgMTAgMCBSIDExIDAgUiAxMiAwIFIgMTMgMCBSIDE0IDAgUiAxNSAwIFIgMTYgMCBSIDE3IDAgUiAxOCAwIFIgMTkgMCBSIDIwIDAgUl0+PgplbmRvYmoKCjUgMCBvYmoKPDwvVHlwZS9Gb250L1N1YnR5cGUvVHlwZTEvQmFzZUZvbnQvSGVsdmV0aWNhL0VuY29kaW5nL1dpbkFuc2lFbmNvZGluZz4+CmVuZG9iagoKNiAwIG9iago8PC9MZW5ndGggNjg+PgpzdHJlYW0KCnEKQlQKMSAwIDAgMSA3MiA3NzAgVG0KL2hlbHYgMTIgVGYgWzwzMjMwMzIzNjJmMzAzNDJmMzIzOD5dVEoKRVQKUQoKZW5kc3RyZWFtCmVuZG9iagoKNyAwIG9iago8PC9MZW5ndGggNjIvRmlsdGVyL0ZsYXRlRGVjb2RlPj4Kc3RyZWFtCnja4yrkcgrhMlQwAEJDBXMjBXNTI4WQXC79jNScMgVDIDtNIdomyRwEjVIgdJK5XWyIF5drCFcgFwDVvA9yCmVuZHN0cmVhbQplbmRvYmoKCjggMCBvYmoKPDwvTGVuZ3RoIDUyPj4Kc3RyZWFtCgpxCkJUCjEgMCAwIDEgNzIgNzM0IFRtCi9oZWx2IDEyIFRmIFs8YjdiNz5dVEoKRVQKUQoKZW5kc3RyZWFtCmVuZG9iagoKOSAwIG9iago8PC9MZW5ndGggNTY+PgpzdHJlYW0KCnEKQlQKMSAwIDAgMSA3MiA3MTYgVG0KL2hlbHYgMTIgVGYgWzwzMWI3YjdiNz5dVEoKRVQKUQoKZW5kc3RyZWFtCmVuZG9iagoKMTAgMCBvYmoKPDwvTGVuZ3RoIDU2Pj4Kc3RyZWFtCgpxCkJUCjEgMCAwIDEgNzIgNjk4IFRtCi9oZWx2IDEyIFRmIFs8MzgzNDMyYjc+XVRKCkVUClEKCmVuZHN0cmVhbQplbmRvYmoKCjExIDAgb2JqCjw8L0xlbmd0aCA2OD4+CnN0cmVhbQoKcQpCVAoxIDAgMCAxIDcyIDY4MCBUbQovaGVsdiAxMiBUZiBbPDMyMzAzMjM2MmYzMDM0MmYzMjM3Pl1USgpFVApRCgplbmRzdHJlYW0KZW5kb2JqCgoxMiAwIG9iago8PC9MZW5ndGggNzI+PgpzdHJlYW0KCnEKQlQKMSAwIDAgMSA3MiA2NjIgVG0KL2hlbHYgMTIgVGYgWzw0MTZkNjE3YTZmNmUyZTYzNmYyZTZhNzA+XVRKCkVUClEKCmVuZHN0cmVhbQplbmRvYmoKCjEzIDAgb2JqCjw8L0xlbmd0aCA1Mj4+CnN0cmVhbQoKcQpCVAoxIDAgMCAxIDcyIDY0NCBUbQovaGVsdiAxMiBUZiBbPGI3Yjc+XVRKCkVUClEKCmVuZHN0cmVhbQplbmRvYmoKCjE0IDAgb2JqCjw8L0xlbmd0aCA1Nj4+CnN0cmVhbQoKcQpCVAoxIDAgMCAxIDcyIDYyNiBUbQovaGVsdiAxMiBUZiBbPDMxYjdiN2I3Pl1USgpFVApRCgplbmRzdHJlYW0KZW5kb2JqCgoxNSAwIG9iago8PC9MZW5ndGggNjA+PgpzdHJlYW0KCnEKQlQKMSAwIDAgMSA3MiA2MDggVG0KL2hlbHYgMTIgVGYgWzwzMzJjMzIzMDMwYjc+XVRKCkVUClEKCmVuZHN0cmVhbQplbmRvYmoKCjE2IDAgb2JqCjw8L0xlbmd0aCA2OD4+CnN0cmVhbQoKcQpCVAoxIDAgMCAxIDcyIDU5MCBUbQovaGVsdiAxMiBUZiBbPDMyMzAzMjM2MmYzMDM0MmYzMjM2Pl1USgpFVApRCgplbmRzdHJlYW0KZW5kb2JqCgoxNyAwIG9iago8PC9MZW5ndGggNjEvRmlsdGVyL0ZsYXRlRGVjb2RlPj4Kc3RyZWFtCnja4yrkcgrhMlQwAEJDBXMjBVMgDsnl0s9IzSlTMASy0xSibZLMk8yNDEAkAtrFhnhxuYZwBXIBABSPEHAKZW5kc3RyZWFtCmVuZG9iagoKMTggMCBvYmoKPDwvTGVuZ3RoIDUyPj4Kc3RyZWFtCgpxCkJUCjEgMCAwIDEgNzIgNTU0IFRtCi9oZWx2IDEyIFRmIFs8YjdiNz5dVEoKRVQKUQoKZW5kc3RyZWFtCmVuZG9iagoKMTkgMCBvYmoKPDwvTGVuZ3RoIDU2Pj4Kc3RyZWFtCgpxCkJUCjEgMCAwIDEgNzIgNTM2IFRtCi9oZWx2IDEyIFRmIFs8MzFiN2I3Yjc+XVRKCkVUClEKCmVuZHN0cmVhbQplbmRvYmoKCjIwIDAgb2JqCjw8L0xlbmd0aCA2MD4+CnN0cmVhbQoKcQpCVAoxIDAgMCAxIDcyIDUxOCBUbQovaGVsdiAxMiBUZiBbPDJkMzEzNTMxMzhiNz5dVEoKRVQKUQoKZW5kc3RyZWFtCmVuZG9iagoKeHJlZgowIDIxCjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDA0MiAwMDAwMCBuIAowMDAwMDAwMTIwIDAwMDAwIG4gCjAwMDAwMDAxNzIgMDAwMDAgbiAKMDAwMDAwMDIxMyAwMDAwMCBuIAowMDAwMDAwNDE1IDAwMDAwIG4gCjAwMDAwMDA1MDQgMDAwMDAgbiAKMDAwMDAwMDYyMSAwMDAwMCBuIAowMDAwMDAwNzUxIDAwMDAwIG4gCjAwMDAwMDA4NTIgMDAwMDAgbiAKMDAwMDAwMDk1NyAwMDAwMCBuIAowMDAwMDAxMDYzIDAwMDAwIG4gCjAwMDAwMDExODEgMDAwMDAgbiAKMDAwMDAwMTMwMyAwMDAwMCBuIAowMDAwMDAxNDA1IDAwMDAwIG4gCjAwMDAwMDE1MTEgMDAwMDAgbiAKMDAwMDAwMTYyMSAwMDAwMCBuIAowMDAwMDAxNzM5IDAwMDAwIG4gCjAwMDAwMDE4NjkgMDAwMDAgbiAKMDAwMDAwMTk3MSAwMDAwMCBuIAowMDAwMDAyMDc3IDAwMDAwIG4gCgp0cmFpbGVyCjw8L1NpemUgMjEvUm9vdCAxIDAgUi9JRFs8MzFDMzg3MDU3MEMzODM2OTE0N0RDMzlEQzI5QkMyQTM+PDA2NDg4M0I0MDVGMDk0MEMxRDI0NzU1Mzc2NDA1NjhEPl0+PgpzdGFydHhyZWYKMjE4NwolJUVPRgo=";

export async function createPdfDataTransfer(page: Page, fileName: string) {
  return page.evaluateHandle(({ name, base64 }) => {
    const dataTransfer = new DataTransfer();
    const binary = atob(base64);
    const content = Uint8Array.from(binary, (char) => char.charCodeAt(0));
    dataTransfer.items.add(new File([content], name, { type: "application/pdf" }));
    return dataTransfer;
  }, { name: fileName, base64: RAKUTEN_STATEMENT_PDF_BASE64 });
}

export async function dropPdfOnUploadZone(page: Page, fileName: string) {
  await page.getByLabel("PDFファイルのドロップゾーン").dispatchEvent("drop", {
    dataTransfer: await createPdfDataTransfer(page, fileName),
  });
}

export async function uploadPdfAndWaitForHistory(page: Page, fileName: string) {
  const uploadResponse = page.waitForResponse((response) =>
    response.url().includes("/api/uploads") && response.request().method() === "POST",
  );

  await dropPdfOnUploadZone(page, fileName);
  await expect(page.getByLabel("アップロード進捗")).toBeVisible();
  await expect(page.getByText(fileName)).toBeVisible();
  await uploadResponse;
  return expectUploadHistoryRow(page, fileName, { status: "完了" });
}

export async function expectUploadHistoryRow(
  page: Page,
  fileName: string,
  options: { status: string; importedCount?: string; errorMessage?: string },
) {
  const row = page.getByRole("row").filter({ hasText: fileName });
  await expect(row).toContainText(options.status);
  if (options.importedCount) {
    await expect(row).toContainText(options.importedCount);
  }
  if (options.errorMessage) {
    await expect(row).toContainText(options.errorMessage);
  }
  return row;
}
