import type { CategoryDto, CategorySummaryDto, TransactionDto, UploadJobDto } from "./types";

export const categories: CategoryDto[] = [
  {
    category_id: "cat_food",
    name: "食費",
    color: "#ff6b7a",
    description: "スーパー、コンビニ、カフェ",
    monthly_budget: 45000,
    is_active: true,
  },
  {
    category_id: "cat_daily",
    name: "日用品",
    color: "#eea932",
    description: "Amazon、ドラッグストア",
    monthly_budget: 12000,
    is_active: true,
  },
  {
    category_id: "cat_transport",
    name: "交通費",
    color: "#38a7e0",
    description: "JR、Suica、地下鉄",
    monthly_budget: 15000,
    is_active: true,
  },
  {
    category_id: "cat_entertainment",
    name: "娯楽",
    color: "#9c72de",
    description: "映画、配信、書籍",
    monthly_budget: 10000,
    is_active: true,
  },
];

export const categorySummary: CategorySummaryDto[] = [
  { category_id: "cat_food", name: "食費", color: "#ff6b7a", amount: 33450, ratio: 0.299 },
  { category_id: "cat_transport", name: "交通費", color: "#38a7e0", amount: 15200, ratio: 0.118 },
  { category_id: "cat_daily", name: "日用品", color: "#eea932", amount: 12100, ratio: 0.096 },
  { category_id: "cat_entertainment", name: "娯楽", color: "#9c72de", amount: 18600, ratio: 0.145 },
];

export const recentTransactions: TransactionDto[] = [
  {
    transaction_id: "txn_001",
    display_category_id: "cat_food",
    transaction_date: "2026-04-28",
    shop_name: "セブン-イレブン",
    category_id: "cat_food",
    category_name: "食費",
    category_color: "#ff6b7a",
    amount: 842,
    transaction_type: "expense",
    payment_method: "クレジットカード",
    card_user_name: null,
    memo: "朝食・おにぎり",
    source_upload_id: null,
    source_file_name: null,
    source_row_number: null,
    source_page_number: null,
    source_format: null,
    source_hash: null,
  },
  {
    transaction_id: "txn_002",
    display_category_id: "cat_daily",
    transaction_date: "2026-04-27",
    shop_name: "Amazon.co.jp",
    category_id: "cat_daily",
    category_name: "日用品",
    category_color: "#eea932",
    amount: 3200,
    transaction_type: "expense",
    payment_method: "クレジットカード",
    card_user_name: null,
    memo: "洗剤・日用品",
    source_upload_id: null,
    source_file_name: null,
    source_row_number: null,
    source_page_number: null,
    source_format: null,
    source_hash: null,
  },
  {
    transaction_id: "txn_003",
    display_category_id: "cat_transport",
    transaction_date: "2026-04-27",
    shop_name: "JR東日本",
    category_id: "cat_transport",
    category_name: "交通費",
    category_color: "#38a7e0",
    amount: 1320,
    transaction_type: "expense",
    payment_method: "Suica",
    card_user_name: null,
    memo: "通勤",
    source_upload_id: null,
    source_file_name: null,
    source_row_number: null,
    source_page_number: null,
    source_format: null,
    source_hash: null,
  },
  {
    transaction_id: "txn_004",
    display_category_id: "cat_entertainment",
    transaction_date: "2026-04-25",
    shop_name: "TOHOシネマズ",
    category_id: "cat_entertainment",
    category_name: "娯楽",
    category_color: "#9c72de",
    amount: 2200,
    transaction_type: "expense",
    payment_method: "クレジットカード",
    card_user_name: null,
    memo: "映画",
    source_upload_id: null,
    source_file_name: null,
    source_row_number: null,
    source_page_number: null,
    source_format: null,
    source_hash: null,
  },
  {
    transaction_id: "txn_005",
    display_category_id: "cat_food",
    transaction_date: "2026-04-24",
    shop_name: "成城石井",
    category_id: "cat_food",
    category_name: "食費",
    category_color: "#ff6b7a",
    amount: 4280,
    transaction_type: "expense",
    payment_method: "デビットカード",
    card_user_name: null,
    memo: "夕食",
    source_upload_id: null,
    source_file_name: null,
    source_row_number: null,
    source_page_number: null,
    source_format: null,
    source_hash: null,
  },
];

export const uploadJobs: UploadJobDto[] = [
  {
    upload_id: "upload_001",
    file_name: "card-statement-2026-04.pdf",
    stored_file_path: "storage/uploads/demo/upload_001/original.pdf",
    status: "completed",
    imported_count: 38,
    error_message: null,
    uploaded_at: "2026-05-01 09:12",
  },
];
